# -*- coding: utf-8 -*-
"""Spam_email_using_lottery_word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNBV3kmpjWbVi4zRA0nIXie2IhxjTaZM
"""

# Required Libraries
import numpy as np

# Given Data
P_Spam = 0.20  # P(Spam)
P_Normal = 0.80  # P(Normal)

P_Lottery_given_Spam = 0.90  # P("lottery" | Spam)
P_Lottery_given_Normal = 0.05  # P("lottery" | Normal)

# Calculate P("lottery")
P_Lottery = (P_Lottery_given_Spam * P_Spam) + (P_Lottery_given_Normal * P_Normal)

# Apply Bayes Theorem to find P(Spam | "lottery")
P_Spam_given_Lottery = (P_Lottery_given_Spam * P_Spam) / P_Lottery

# Output the result
print("P(Spam | 'lottery') =", P_Spam_given_Lottery)